version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "pom.xml" }}
    - run: cat /dev/null | mvn clean package
    - run: |
        mkdir -p ~/tests/jUnit/
        find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/tests/jUnit/ \;
    - store_test_results:
        path: ~/tests
    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml" }}
